### ISSUE TITLE
Update references to GENI to Clearinghouse

### ISSUE THREAD

**Issue by choksi81** [SeattleTestbed/custominstallerbuilder#1]
This is to reflect the current state of the project, given that we are no longer under the GENI project.

Pages complete:

Pages in progress:
'''(file/link references left unchanged)'''
https://seattle.cs.washington.edu/wiki/SeattleGeniProductionHttp
https://seattle.cs.washington.edu/wiki/SeattleGeniInstallation
https://seattle.cs.washington.edu/wiki/EducationalAssignments/TakeHome
https://seattle.cs.washington.edu/wiki/ContributorsPage
https://seattle.cs.washington.edu/wiki/SeattleGeniClientLib
https://seattle.cs.washington.edu/wiki/SeattleGeniApi

https://seattle.cs.washington.edu/wiki/SeattleLib (stopped after "serialize.py")

Pages not started (INCOMPLETE):

**Comment by aaaaalbert** [comment]
Not an issue anymore for the custominstallerbuilder. Closing!
