### ISSUE TITLE
Need changes to find repy_runtime

### ISSUE THREAD

**Issue by asm582** [SeattleTestbed/custominstallerbuilder#10]
In the link https://seattle.poly.edu/wiki/CustomInstallerBuilderConfiguration we see that repy_runtime should be placed under ~/custominstallerbuilder/repy_runtime but actually we build repy_runtime under  ~ dir. when we configure apache it throws an error if repy_runtime is not found under ~ dir. i tried to modify wsgi.py to actually tell apache to search repy_runtime under ~/custominstallerbuilder/ dir. Do we need to mention the same in our installation instruction?

**Comment by aaaaalbert** [comment]
I believe the instructions are correct, but maybe I'm missing the obvious.

@kaushik1091 can probably chime in on how the correct dir layout (with respect to #6, updating the Django version we use) should look like.

**Comment by lukpueh** [comment]
I *accidentally* fixed this in the docs conversion see SeattlTestbed/docs [PR 14] (https://github.com/SeattleTestbed/docs/pull/14)

**Comment by aaaaalbert** [comment]
@lukpueh: OK, cool! Let's review and merge.

**Comment by aaaaalbert** [comment]
I just *deliberately* merged #14 which, as @lukpueh [indicates above](https://github.com/SeattleTestbed/custominstallerbuilder/issues/10#issuecomment-219859131), also resolve this `repy_runtime` path confusion.
